spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    import: "optional:classpath:application-secret.yml"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        transaction:
          jta:
            platform: org.hibernate.service.jta.JtaPlatform
        dialect: org.hibernate.dialect.MySQL8Dialect